apiVersion: apps/v13
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 13
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 6shihab/example-voting-app_result:13
        name: result
        ports:
        - containerPort: 80
          name: result
