apiVersion: apps/v18
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 18
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: 6shihab/example-voting-app_vote:18
        name: vote
        ports:
        - containerPort: 80
          name: vote
