apiVersion: apps/v
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: 6shihab/example-voting-app_worker:
        name: worker
