apiVersion: apps/v13
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 13
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: 6shihab/example-voting-app_worker:13
        name: worker
